import type {
  Brand,
  Category,
  Laboratory,
  Product,
  ProductLot,
} from "@/types";
import { mockBusiness } from "./tenancy";
import { importedBrands, importedProducts } from "./catalog-imported";

const now = "2026-05-05T09:00:00Z";

const seedBrands: Brand[] = [
  { id: "br_sesderma", businessId: mockBusiness.id, name: "SESDERMA", productCount: 83, createdAt: now, updatedAt: now },
  { id: "br_eucerin", businessId: mockBusiness.id, name: "EUCERIN", productCount: 63, createdAt: now, updatedAt: now },
  { id: "br_uriage", businessId: mockBusiness.id, name: "URIAGE", productCount: 62, createdAt: now, updatedAt: now },
  { id: "br_lrp", businessId: mockBusiness.id, name: "LA ROCHE-POSAY", productCount: 75, createdAt: now, updatedAt: now },
  { id: "br_acm", businessId: mockBusiness.id, name: "ACM", productCount: 53, createdAt: now, updatedAt: now },
  { id: "br_avene", businessId: mockBusiness.id, name: "AVÈNE", productCount: 53, createdAt: now, updatedAt: now },
  { id: "br_isispharma", businessId: mockBusiness.id, name: "ISISPHARMA", productCount: 44, createdAt: now, updatedAt: now },
  { id: "br_isdin", businessId: mockBusiness.id, name: "ISDIN", productCount: 38, createdAt: now, updatedAt: now },
  { id: "br_bioderma", businessId: mockBusiness.id, name: "BIODERMA", productCount: 36, createdAt: now, updatedAt: now },
  { id: "br_vichy", businessId: mockBusiness.id, name: "VICHY", productCount: 25, createdAt: now, updatedAt: now },
  { id: "br_heliocare", businessId: mockBusiness.id, name: "HELIOCARE", productCount: 24, createdAt: now, updatedAt: now },
  { id: "br_cerave", businessId: mockBusiness.id, name: "CERAVE", productCount: 21, createdAt: now, updatedAt: now },
  { id: "br_filorga", businessId: mockBusiness.id, name: "FILORGA", productCount: 16, createdAt: now, updatedAt: now },
];

/** Marcas del seed + marcas importadas del Excel (dedupe por id). */
export const mockBrands: Brand[] = [
  ...seedBrands,
  ...importedBrands.filter((b) => !seedBrands.some((s) => s.id === b.id)),
];

export const mockLaboratories: Laboratory[] = [
  { id: "lab_loreal", businessId: mockBusiness.id, name: "L'Oréal Active Cosmetics", country: "Francia", createdAt: now, updatedAt: now },
  { id: "lab_beiersdorf", businessId: mockBusiness.id, name: "Beiersdorf", country: "Alemania", createdAt: now, updatedAt: now },
  { id: "lab_pierre_fabre", businessId: mockBusiness.id, name: "Pierre Fabre", country: "Francia", createdAt: now, updatedAt: now },
  { id: "lab_isdin_lab", businessId: mockBusiness.id, name: "ISDIN", country: "España", createdAt: now, updatedAt: now },
  { id: "lab_naos", businessId: mockBusiness.id, name: "NAOS / Bioderma", country: "Francia", createdAt: now, updatedAt: now },
  { id: "lab_sesderma_lab", businessId: mockBusiness.id, name: "SESDERMA Labs", country: "España", createdAt: now, updatedAt: now },
  { id: "lab_iqfarma", businessId: mockBusiness.id, name: "IQFarma RD", country: "República Dominicana", createdAt: now, updatedAt: now },
];

export const mockCategories: Category[] = [
  { id: "cat_facial", businessId: mockBusiness.id, name: "Cuidado facial", description: "Limpieza, hidratación, antiedad", createdAt: now, updatedAt: now },
  { id: "cat_corporal", businessId: mockBusiness.id, name: "Cuidado corporal", description: "Hidratantes, antiestrías, exfoliantes", createdAt: now, updatedAt: now },
  { id: "cat_solar", businessId: mockBusiness.id, name: "Protección solar", description: "Bloqueadores SPF y after-sun", createdAt: now, updatedAt: now },
  { id: "cat_capilar", businessId: mockBusiness.id, name: "Capilar / Tricología", description: "Shampoos dermatológicos, tratamientos caída", createdAt: now, updatedAt: now },
  { id: "cat_acne", businessId: mockBusiness.id, name: "Acné y piel grasa", description: "Productos con ácido salicílico, niacinamida", createdAt: now, updatedAt: now },
  { id: "cat_atopica", businessId: mockBusiness.id, name: "Piel atópica / sensible", description: "Pieles reactivas, dermatitis", createdAt: now, updatedAt: now },
  { id: "cat_pediatria", businessId: mockBusiness.id, name: "Pediatría dermatológica", description: "Bebés y niños", createdAt: now, updatedAt: now },
  { id: "cat_oral", businessId: mockBusiness.id, name: "Suplementos orales", description: "Cápsulas, complementos para piel/cabello", createdAt: now, updatedAt: now },
  { id: "cat_higiene", businessId: mockBusiness.id, name: "Higiene íntima", description: "Productos pH equilibrado", createdAt: now, updatedAt: now },
  { id: "cat_post_proc", businessId: mockBusiness.id, name: "Post-procedimiento", description: "Cicatrización, cuidado post-clínica", createdAt: now, updatedAt: now },
];

const baseProducts: Omit<Product, "createdAt" | "updatedAt" | "businessId">[] = [
  {
    id: "prod_lrp_001",
    sku: "DERM-000034",
    barcode: "8432598722845",
    name: "La Roche-Posay Toleriane Sensitive Crema 40 ml",
    description: "Hidratante prebiótica para piel sensible. Sin perfume.",
    brandId: "br_lrp",
    laboratoryId: "lab_loreal",
    categoryId: "cat_atopica",
    unit: "unidad",
    pharmaceuticalForm: "crema",
    presentation: "Tubo 40 ml",
    activeIngredient: "Niacinamida + Prebióticos",
    concentration: "1.5%",
    requiresPrescription: false,
    controlled: false,
    cost: 850,
    price: 1250,
    itbisRate: 18,
    minStock: 8,
    maxStock: 60,
    imageUrl: "https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//l/a/la-roche-posay-toleriane-sensitive-cream-40ml_1.jpg",
    imageAlt: "La Roche-Posay Toleriane Sensitive Crema 40 ml",
    imageSourceUrl: "https://www.caretobeauty.com/us/la-roche-posay-toleriane-sensitive-cream-40ml/",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_eu_002",
    sku: "DERM-000018",
    barcode: "4005800189234",
    name: "Eucerin Sun Protection Pigment Control SPF 50+ 50 ml",
    description: "Bloqueador con thiamidol que reduce manchas.",
    brandId: "br_eucerin",
    laboratoryId: "lab_beiersdorf",
    categoryId: "cat_solar",
    unit: "unidad",
    pharmaceuticalForm: "crema",
    presentation: "Tubo 50 ml",
    activeIngredient: "Thiamidol + filtros UV",
    concentration: "SPF 50+",
    requiresPrescription: false,
    controlled: false,
    cost: 1200,
    price: 1890,
    itbisRate: 18,
    minStock: 10,
    maxStock: 80,
    imageUrl: "https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//e/u/eucerin-sun-pigment-control-sun-fluid-spf50-50ml_1.jpg",
    imageAlt: "Eucerin Sun Protection Pigment Control SPF 50+ 50 ml",
    imageSourceUrl: "https://www.caretobeauty.com/us/eucerin-sun-pigment-control-sun-fluid-spf50-50ml/",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_ses_003",
    sku: "DERM-000091",
    barcode: "8429979120014",
    name: "Sesderma C-VIT Sérum Liposomal 30 ml",
    brandId: "br_sesderma",
    laboratoryId: "lab_sesderma_lab",
    categoryId: "cat_facial",
    unit: "unidad",
    pharmaceuticalForm: "serum",
    presentation: "Frasco 30 ml",
    activeIngredient: "Vitamina C liposomada",
    concentration: "5%",
    requiresPrescription: false,
    controlled: false,
    cost: 1850,
    price: 2450,
    itbisRate: 18,
    minStock: 5,
    maxStock: 40,
    imageUrl: "https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//s/e/sesderma-c-vit-serum-liposomal-30ml_1.jpg",
    imageAlt: "Sesderma C-VIT Sérum Liposomal 30 ml",
    imageSourceUrl: "https://www.caretobeauty.com/us/sesderma-c-vit-serum-liposomal-30ml/",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_uri_004",
    sku: "DERM-000122",
    barcode: "3661434006214",
    name: "Uriage Bariéderm Cica-Crema reparadora 100 ml",
    brandId: "br_uriage",
    laboratoryId: "lab_pierre_fabre",
    categoryId: "cat_post_proc",
    unit: "unidad",
    pharmaceuticalForm: "crema",
    presentation: "Tubo 100 ml",
    activeIngredient: "Centella asiática + Cobre/Zinc",
    requiresPrescription: false,
    controlled: false,
    cost: 980,
    price: 1490,
    itbisRate: 18,
    minStock: 6,
    maxStock: 30,
    imageUrl: "https://cdn1.costatic.com/img/product/400/668be898bf1c7/uriage-bariederm-cica-p24730.jpg",
    imageAlt: "Uriage Bariéderm Cica-Crema reparadora 100 ml",
    imageSourceUrl: "https://www.cocooncenter.co.uk/uriage-bariederm-cica-repairing-cream-100ml/28071.html",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_isd_005",
    sku: "DERM-000201",
    barcode: "8470001834561",
    name: "ISDIN Fotoprotector Fusion Water SPF 50 50 ml",
    brandId: "br_isdin",
    laboratoryId: "lab_isdin_lab",
    categoryId: "cat_solar",
    unit: "unidad",
    pharmaceuticalForm: "gel",
    presentation: "Frasco 50 ml",
    requiresPrescription: false,
    controlled: false,
    cost: 1300,
    price: 1990,
    itbisRate: 18,
    minStock: 12,
    maxStock: 100,
    imageUrl: "https://cdn11.bigcommerce.com/s-9xjhkkb3r4/products/289/images/9851/isdin-fusion-water-magic-spf50-50-ml__96881.1741615925.386.513.jpg?c=2",
    imageAlt: "ISDIN Fotoprotector Fusion Water SPF 50 50 ml",
    imageSourceUrl: "https://skincolor.net/isdin-fusion-water-magic-spf50-50-ml/",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_avn_006",
    sku: "DERM-000288",
    barcode: "3282770114451",
    name: "Avène Cleanance Gel Limpiador 200 ml",
    brandId: "br_avene",
    laboratoryId: "lab_pierre_fabre",
    categoryId: "cat_acne",
    unit: "unidad",
    pharmaceuticalForm: "gel",
    presentation: "Frasco 200 ml",
    activeIngredient: "Monolaurin + Ácido salicílico",
    requiresPrescription: false,
    controlled: false,
    cost: 690,
    price: 1090,
    itbisRate: 18,
    minStock: 8,
    maxStock: 50,
    imageUrl: "https://static.thcdn.com/productimg/original/13277516-2005343993762189.jpg",
    imageAlt: "Avène Cleanance Gel Limpiador 200 ml",
    imageSourceUrl: "https://www.dermstore.com/p/avene-cleanance-cleansing-gel-200ml/13277516/",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_bio_007",
    sku: "DERM-000312",
    barcode: "3401345643218",
    name: "Bioderma Sensibio H2O Agua micelar 500 ml",
    brandId: "br_bioderma",
    laboratoryId: "lab_naos",
    categoryId: "cat_facial",
    unit: "unidad",
    pharmaceuticalForm: "locion",
    presentation: "Frasco 500 ml",
    requiresPrescription: false,
    controlled: false,
    cost: 980,
    price: 1450,
    itbisRate: 18,
    minStock: 10,
    maxStock: 60,
    imageUrl: "https://dermotiendashopping.com/cdn/shop/files/DSC05004.jpg?v=1770130936&width=3840",
    imageAlt: "Bioderma Sensibio H2O Agua micelar 500 ml",
    imageSourceUrl: "https://dermotiendashopping.com/products/bioderma-sensibio-h2o-500ml",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_cer_008",
    sku: "DERM-000356",
    barcode: "3606000540125",
    name: "CeraVe Limpiador Hidratante 236 ml",
    brandId: "br_cerave",
    laboratoryId: "lab_loreal",
    categoryId: "cat_facial",
    unit: "unidad",
    pharmaceuticalForm: "locion",
    presentation: "Frasco 236 ml",
    activeIngredient: "Ceramidas + Ácido hialurónico",
    requiresPrescription: false,
    controlled: false,
    cost: 720,
    price: 1090,
    itbisRate: 18,
    minStock: 12,
    maxStock: 80,
    imageUrl: "https://dermotiendashopping.com/cdn/shop/files/3337875597180_1.png?v=1765834526&width=3840",
    imageAlt: "CeraVe Limpiador Hidratante 236 ml",
    imageSourceUrl: "https://dermotiendashopping.com/products/cerave-limpiador-hidratante-236ml",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_vch_009",
    sku: "DERM-000412",
    barcode: "3337875778978",
    name: "Vichy Mineral 89 Booster hidratante 50 ml",
    brandId: "br_vichy",
    laboratoryId: "lab_loreal",
    categoryId: "cat_facial",
    unit: "unidad",
    pharmaceuticalForm: "serum",
    presentation: "Frasco 50 ml",
    requiresPrescription: false,
    controlled: false,
    cost: 1450,
    price: 2190,
    itbisRate: 18,
    minStock: 5,
    maxStock: 35,
    imageUrl: "https://frenchpharmacy.com/cdn/shop/products/Vichy_Mineral89_large.jpg?v=1560977334",
    imageAlt: "Vichy Mineral 89 Booster hidratante 50 ml",
    imageSourceUrl: "https://frenchpharmacy.com/products/vichy-mineral-89-daily-booster",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_hlc_010",
    sku: "DERM-000477",
    barcode: "8470001785633",
    name: "Heliocare 360º Oral Cápsulas 30 unid.",
    brandId: "br_heliocare",
    categoryId: "cat_oral",
    unit: "caja",
    pharmaceuticalForm: "capsula",
    presentation: "Caja 30 cáps.",
    requiresPrescription: false,
    controlled: false,
    cost: 1850,
    price: 2790,
    itbisRate: 18,
    minStock: 4,
    maxStock: 25,
    imageUrl: "https://farmaciadermedica.com/cdn/shop/products/cantabria-labs-heliocare-360-capsulas_1024x.jpg?v=1750478352",
    imageAlt: "Heliocare 360º Oral Cápsulas 30 unidades",
    imageSourceUrl: "https://farmaciadermedica.com/products/heliocare-360-oral-30-capsulas",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_acm_011",
    sku: "DERM-000523",
    barcode: "3760095250112",
    name: "ACM Sebionex Gel limpiador 200 ml",
    brandId: "br_acm",
    categoryId: "cat_acne",
    unit: "unidad",
    pharmaceuticalForm: "gel",
    presentation: "Frasco 200 ml",
    requiresPrescription: false,
    controlled: false,
    cost: 540,
    price: 890,
    itbisRate: 18,
    minStock: 6,
    maxStock: 30,
    imageUrl: "https://pielfarmaceutica.com/cdn/shop/files/download_51ccc435-5810-489a-9839-178cd66c42b0.jpg?v=1712164717&width=1946",
    imageAlt: "ACM Sebionex Gel limpiador 200 ml",
    imageSourceUrl: "https://pielfarmaceutica.com/products/acm-sebionex-gel-limpiador-x-200ml",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
  {
    id: "prod_isi_012",
    sku: "DERM-000601",
    barcode: "3760116490012",
    name: "Isispharma Ruboril Expert Sérum Anti-Rojeces 30 ml",
    brandId: "br_isispharma",
    categoryId: "cat_atopica",
    unit: "unidad",
    pharmaceuticalForm: "serum",
    presentation: "Frasco 30 ml",
    requiresPrescription: false,
    controlled: false,
    cost: 1690,
    price: 2390,
    itbisRate: 18,
    minStock: 4,
    maxStock: 22,
    imageUrl: "https://www.soin-et-nature.com/media/cache/shop_product_large_thumbnail/products/4/7/5/9/7/47597.jpg",
    imageAlt: "Isispharma Ruboril Expert Sérum Anti-Rojeces 30 ml",
    imageSourceUrl: "https://www.soin-et-nature.com/en/25407-isispharma-ruboril-expert-intense-concentrated-anti-redness-care-15ml.html",
    imageStatus: "linked",
    active: true,
    sellable: true,
  },
];

const seedProducts: Product[] = baseProducts.map((p) => ({
  ...p,
  businessId: mockBusiness.id,
  createdAt: now,
  updatedAt: now,
}));

/** Productos del seed (12 detallados) + catálogo importado del Excel. */
export const mockProducts: Product[] = [...seedProducts, ...importedProducts];

const day = (offsetDays: number) => {
  const d = new Date("2026-05-05T00:00:00Z");
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString();
};

export const mockProductLots: ProductLot[] = [
  // LRP Toleriane — 2 lotes, uno cerca de vencer
  {
    id: "lot_lrp_001a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_lrp_001",
    warehouseId: "wh_stg_main",
    lotNumber: "LRP24A",
    expiresAt: day(45),
    receivedAt: day(-90),
    initialQuantity: 36,
    currentQuantity: 18,
    unitCost: 850,
    status: "available",
    supplierId: "sup_loreal_rd",
    purchaseInvoice: "B0100000234",
    createdAt: day(-90),
    updatedAt: day(-2),
  },
  {
    id: "lot_lrp_001b",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_lrp_001",
    warehouseId: "wh_stg_main",
    lotNumber: "LRP24B",
    expiresAt: day(420),
    receivedAt: day(-30),
    initialQuantity: 24,
    currentQuantity: 24,
    unitCost: 870,
    status: "available",
    createdAt: day(-30),
    updatedAt: day(-30),
  },
  // EU bloqueador — vencido
  {
    id: "lot_eu_002a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_eu_002",
    warehouseId: "wh_stg_main",
    lotNumber: "EU23X",
    expiresAt: day(-15),
    receivedAt: day(-300),
    initialQuantity: 18,
    currentQuantity: 6,
    unitCost: 1200,
    status: "expired",
    createdAt: day(-300),
    updatedAt: day(-1),
  },
  {
    id: "lot_eu_002b",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_eu_002",
    warehouseId: "wh_stg_main",
    lotNumber: "EU24C",
    expiresAt: day(720),
    receivedAt: day(-15),
    initialQuantity: 30,
    currentQuantity: 28,
    unitCost: 1220,
    status: "available",
    createdAt: day(-15),
    updatedAt: day(-1),
  },
  // SES C-VIT
  {
    id: "lot_ses_003a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_ses_003",
    warehouseId: "wh_stg_main",
    lotNumber: "SES24-CV",
    expiresAt: day(180),
    receivedAt: day(-60),
    initialQuantity: 15,
    currentQuantity: 9,
    unitCost: 1850,
    status: "available",
    createdAt: day(-60),
    updatedAt: day(-3),
  },
  // Uriage Cica
  {
    id: "lot_uri_004a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_uri_004",
    warehouseId: "wh_stg_main",
    lotNumber: "URI24-BAR",
    expiresAt: day(540),
    receivedAt: day(-25),
    initialQuantity: 18,
    currentQuantity: 14,
    unitCost: 980,
    status: "available",
    createdAt: day(-25),
    updatedAt: day(-1),
  },
  // ISDIN — cuarentena
  {
    id: "lot_isd_005a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_isd_005",
    warehouseId: "wh_stg_main",
    lotNumber: "ISD24-FW",
    expiresAt: day(360),
    receivedAt: day(-12),
    initialQuantity: 24,
    currentQuantity: 24,
    unitCost: 1300,
    status: "quarantine",
    notes: "Pendiente verificación de cadena de frío",
    createdAt: day(-12),
    updatedAt: day(-2),
  },
  // Avene Cleanance
  {
    id: "lot_avn_006a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_avn_006",
    warehouseId: "wh_stg_main",
    lotNumber: "AVN24-CLE",
    expiresAt: day(75),
    receivedAt: day(-20),
    initialQuantity: 30,
    currentQuantity: 22,
    unitCost: 690,
    status: "available",
    createdAt: day(-20),
    updatedAt: day(-1),
  },
  // Bioderma
  {
    id: "lot_bio_007a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_bio_007",
    warehouseId: "wh_stg_main",
    lotNumber: "BIO24-SH",
    expiresAt: day(600),
    receivedAt: day(-30),
    initialQuantity: 30,
    currentQuantity: 19,
    unitCost: 980,
    status: "available",
    createdAt: day(-30),
    updatedAt: day(-1),
  },
  // CeraVe
  {
    id: "lot_cer_008a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_cer_008",
    warehouseId: "wh_stg_main",
    lotNumber: "CER24-HC",
    expiresAt: day(540),
    receivedAt: day(-18),
    initialQuantity: 36,
    currentQuantity: 31,
    unitCost: 720,
    status: "available",
    createdAt: day(-18),
    updatedAt: day(-2),
  },
  // Vichy
  {
    id: "lot_vch_009a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_vch_009",
    warehouseId: "wh_stg_main",
    lotNumber: "VCH24-M89",
    expiresAt: day(800),
    receivedAt: day(-7),
    initialQuantity: 12,
    currentQuantity: 12,
    unitCost: 1450,
    status: "available",
    createdAt: day(-7),
    updatedAt: day(-7),
  },
  // Heliocare oral
  {
    id: "lot_hlc_010a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_hlc_010",
    warehouseId: "wh_stg_main",
    lotNumber: "HLC24-30",
    expiresAt: day(900),
    receivedAt: day(-10),
    initialQuantity: 12,
    currentQuantity: 7,
    unitCost: 1850,
    status: "available",
    createdAt: day(-10),
    updatedAt: day(-1),
  },
  // ACM
  {
    id: "lot_acm_011a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_acm_011",
    warehouseId: "wh_stg_main",
    lotNumber: "ACM24-SEB",
    expiresAt: day(420),
    receivedAt: day(-22),
    initialQuantity: 18,
    currentQuantity: 5,
    unitCost: 540,
    status: "available",
    createdAt: day(-22),
    updatedAt: day(-1),
  },
  // Isispharma — recall
  {
    id: "lot_isi_012a",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    productId: "prod_isi_012",
    warehouseId: "wh_stg_main",
    lotNumber: "ISI24-RUB",
    expiresAt: day(300),
    receivedAt: day(-40),
    initialQuantity: 12,
    currentQuantity: 8,
    unitCost: 1690,
    status: "recalled",
    notes: "Recall fabricante por irregularidad de envasado",
    createdAt: day(-40),
    updatedAt: day(-1),
  },
];

export function getProductById(id: string) {
  return mockProducts.find((p) => p.id === id);
}

export function getBrandById(id: string | undefined) {
  return id ? mockBrands.find((b) => b.id === id) : undefined;
}

export function getCategoryById(id: string | undefined) {
  return id ? mockCategories.find((c) => c.id === id) : undefined;
}

export function getLaboratoryById(id: string | undefined) {
  return id ? mockLaboratories.find((l) => l.id === id) : undefined;
}

export function getLotsByProduct(productId: string) {
  return mockProductLots.filter((l) => l.productId === productId);
}

export function getProductByBarcode(barcode: string) {
  return mockProducts.find((p) => p.barcode === barcode);
}

export function totalStockForProduct(productId: string) {
  return mockProductLots
    .filter((l) => l.productId === productId && l.status === "available")
    .reduce((s, l) => s + l.currentQuantity, 0);
}

export function selectFefoLot(productId: string) {
  const lots = mockProductLots
    .filter((l) => l.productId === productId && l.status === "available" && l.currentQuantity > 0)
    .sort((a, b) => new Date(a.expiresAt).getTime() - new Date(b.expiresAt).getTime());
  return lots[0];
}
