import type {
  Recommendation,
  RoutineTemplate,
  SkinCondition,
  SkinType,
} from "@/types";
import { mockBusiness } from "./tenancy";

export const mockSkinTypes: SkinType[] = [
  {
    key: "dry",
    label: "Seca",
    description:
      "Piel con baja producción de sebo. Tendencia a tirantez, descamación y opacidad.",
    characteristics: [
      "Sensación de tirantez tras lavar",
      "Apariencia opaca o áspera",
      "Líneas finas más visibles",
      "Reacciona al frío y al viento",
    ],
    recommendedIngredients: [
      "Ácido hialurónico",
      "Glicerina",
      "Ceramidas",
      "Manteca de karité",
      "Escualano",
    ],
    avoidIngredients: ["Alcohol denat.", "Tensoactivos sulfatados"],
  },
  {
    key: "oily",
    label: "Grasa",
    description:
      "Sobreproducción de sebo, brillo en zona T, tendencia a poros dilatados y comedones.",
    characteristics: [
      "Brillo persistente en frente, nariz y mentón",
      "Poros visibles",
      "Comedones y puntos negros",
      "Tendencia a brotes de acné",
    ],
    recommendedIngredients: [
      "Niacinamida",
      "Ácido salicílico",
      "Zinc PCA",
      "Retinoides tópicos",
      "Arcilla",
    ],
    avoidIngredients: ["Aceites comedogénicos pesados"],
  },
  {
    key: "combination",
    label: "Mixta",
    description: "Zona T grasa, mejillas normales o secas.",
    characteristics: [
      "Brillo en zona T",
      "Sequedad o normalidad en mejillas",
      "Poros dilatados centrales",
    ],
    recommendedIngredients: ["Niacinamida", "Ácido hialurónico", "Aloe vera"],
    avoidIngredients: ["Cremas muy oclusivas en zona T"],
  },
  {
    key: "normal",
    label: "Normal",
    description: "Equilibrio entre hidratación y sebo. Buen tono.",
    characteristics: ["Textura suave", "Poros poco visibles", "Sin brotes frecuentes"],
    recommendedIngredients: ["Vitamina C", "Hidratantes ligeros", "Antioxidantes"],
    avoidIngredients: [],
  },
  {
    key: "sensitive",
    label: "Sensible / reactiva",
    description: "Reacciona con enrojecimiento, picor o ardor a estímulos comunes.",
    characteristics: [
      "Enrojecimiento frecuente",
      "Sensación de ardor o picor",
      "Reacciona a perfumes y alcohol",
    ],
    recommendedIngredients: [
      "Centella asiática",
      "Pantenol",
      "Avena coloidal",
      "Madecassoside",
      "Niacinamida (concentración baja)",
    ],
    avoidIngredients: [
      "Alcohol denat.",
      "Perfumes",
      "Aceites esenciales fuertes",
      "Ácidos en alta concentración",
    ],
  },
  {
    key: "mature",
    label: "Madura",
    description:
      "Piel con signos de envejecimiento: pérdida de firmeza, líneas, manchas.",
    characteristics: [
      "Líneas finas y arrugas",
      "Pérdida de elasticidad",
      "Manchas pigmentarias",
      "Sequedad acentuada",
    ],
    recommendedIngredients: [
      "Retinol",
      "Vitamina C",
      "Péptidos",
      "Resveratrol",
      "Bakuchiol",
    ],
    avoidIngredients: [],
  },
];

export const mockSkinConditions: SkinCondition[] = [
  {
    id: "cond_acne",
    name: "Acné inflamatorio",
    description: "Brotes con pápulas, pústulas y comedones.",
    severity: "moderate",
    commonIngredients: [
      "Ácido salicílico 0.5–2%",
      "Peróxido de benzoilo 2.5%",
      "Niacinamida",
      "Retinoides tópicos",
    ],
    warnings: [
      "Evitar combinar peróxido con retinol simultáneamente",
      "Aplicar SPF 50+ diario obligatorio",
    ],
  },
  {
    id: "cond_rosacea",
    name: "Rosácea / piel reactiva",
    description: "Eritema persistente, telangiectasias, reactividad alta.",
    severity: "moderate",
    commonIngredients: ["Madecassoside", "Centella asiática", "Niacinamida"],
    warnings: [
      "Evitar alcohol, perfumes, agua muy caliente",
      "Prohibido peeling AHA/BHA en fase aguda",
    ],
  },
  {
    id: "cond_melasma",
    name: "Melasma / hiperpigmentación",
    description: "Manchas simétricas en mejillas, frente y labio superior.",
    severity: "moderate",
    commonIngredients: [
      "Thiamidol",
      "Tranexámico",
      "Vitamina C",
      "Niacinamida",
      "Azelaico 10–20%",
    ],
    warnings: ["SPF 50+ obligatorio diario", "Evitar exposición solar directa"],
  },
  {
    id: "cond_atopic",
    name: "Dermatitis atópica",
    description: "Piel reactiva con prurito y placas eccematosas.",
    severity: "moderate",
    commonIngredients: ["Ceramidas", "Avena coloidal", "Pantenol", "Glicerina"],
    warnings: ["Evitar fragancias", "Hidratar 2-3 veces al día"],
  },
  {
    id: "cond_aging",
    name: "Antiedad / fotoenvejecimiento",
    description: "Líneas finas, pérdida de firmeza, manchas asociadas al sol.",
    severity: "mild",
    commonIngredients: ["Retinol", "Péptidos", "Vitamina C", "Bakuchiol"],
    warnings: ["Iniciar retinol gradual cada 3 noches", "SPF 50+ diario"],
  },
  {
    id: "cond_dehydration",
    name: "Deshidratación",
    description: "Pérdida de agua transepidérmica, sensación de tirantez.",
    severity: "mild",
    commonIngredients: ["Ácido hialurónico", "Glicerina", "Pantenol", "Urea 5%"],
    warnings: [],
  },
  {
    id: "cond_alopecia",
    name: "Caída capilar / alopecia",
    description: "Caída excesiva del cabello, debilitamiento.",
    severity: "moderate",
    commonIngredients: ["Minoxidil 5%", "Biotina", "Cafeína tópica"],
    warnings: ["Constancia mínima 3-6 meses", "Consultar dermatólogo si persiste"],
  },
];

export const mockRoutineTemplates: RoutineTemplate[] = [
  {
    id: "rt_acne_basic",
    name: "Rutina anti-acné básica",
    skinTypes: ["oily", "combination"],
    conditions: ["cond_acne"],
    description: "Rutina dual diaria para piel grasa con tendencia a acné.",
    steps: [
      {
        order: 1,
        moment: "morning",
        category: "Limpieza",
        productSuggestion: "ACM Sebionex / Avène Cleanance gel",
        instructions: "Aplicar con manos limpias, masajear 30s y enjuagar.",
      },
      {
        order: 2,
        moment: "morning",
        category: "Tratamiento",
        productSuggestion: "Niacinamida 10% sérum",
        instructions: "1-2 gotas en rostro seco.",
      },
      {
        order: 3,
        moment: "morning",
        category: "Hidratación",
        productSuggestion: "Hidratante oil-free",
        instructions: "Capa fina, cubrir todo el rostro.",
      },
      {
        order: 4,
        moment: "morning",
        category: "Protección solar",
        productSuggestion: "ISDIN Fusion Water SPF 50",
        instructions: "Reaplicar cada 2-3 h al estar al sol.",
      },
      {
        order: 5,
        moment: "evening",
        category: "Limpieza",
        instructions: "Doble limpieza con micelar + gel limpiador.",
      },
      {
        order: 6,
        moment: "evening",
        category: "Tratamiento",
        productSuggestion: "Ácido salicílico 2% noche alterna",
        instructions: "Aplicar en zona afectada, no rostro completo.",
      },
      {
        order: 7,
        moment: "evening",
        category: "Hidratación",
        productSuggestion: "Hidratante reparador no comedogénico",
        instructions: "Sellar la rutina con hidratación ligera.",
      },
    ],
  },
  {
    id: "rt_sensitive",
    name: "Rutina piel sensible / rosácea",
    skinTypes: ["sensitive"],
    conditions: ["cond_rosacea"],
    description: "Rutina ultra-suave para reducir reactividad y enrojecimiento.",
    steps: [
      {
        order: 1,
        moment: "morning",
        category: "Limpieza",
        productSuggestion: "Bioderma Sensibio H2O",
        instructions: "Limpieza con algodón, sin enjuague agresivo.",
      },
      {
        order: 2,
        moment: "morning",
        category: "Tratamiento",
        productSuggestion: "Isispharma Ruboril Expert sérum anti-rojeces",
        instructions: "Aplicar 2-3 gotas en zonas reactivas.",
      },
      {
        order: 3,
        moment: "morning",
        category: "Hidratación",
        productSuggestion: "La Roche-Posay Toleriane Sensitive crema",
        instructions: "Capa generosa, masaje suave.",
      },
      {
        order: 4,
        moment: "morning",
        category: "Protección solar",
        productSuggestion: "Avène Mineral SPF 50",
        instructions: "Filtros minerales, reaplicar cada 2 h.",
      },
      {
        order: 5,
        moment: "evening",
        category: "Limpieza",
        instructions: "Mismo limpiador suave que en mañana.",
      },
      {
        order: 6,
        moment: "evening",
        category: "Hidratación",
        productSuggestion: "Toleriane Sensitive crema",
        instructions: "Volver a aplicar antes de dormir.",
      },
    ],
  },
  {
    id: "rt_antiage",
    name: "Rutina antiedad / firmeza",
    skinTypes: ["mature", "normal"],
    conditions: ["cond_aging"],
    description: "Rutina con retinol y vitamina C para fotoenvejecimiento.",
    steps: [
      {
        order: 1,
        moment: "morning",
        category: "Limpieza",
        instructions: "Limpieza suave en seco o húmedo.",
      },
      {
        order: 2,
        moment: "morning",
        category: "Antioxidante",
        productSuggestion: "Sesderma C-VIT Liposomal sérum",
        instructions: "1-2 gotas en rostro seco antes de hidratar.",
      },
      {
        order: 3,
        moment: "morning",
        category: "Hidratación",
        productSuggestion: "Vichy Mineral 89 booster",
        instructions: "Sella la vitamina C.",
      },
      {
        order: 4,
        moment: "morning",
        category: "Protección solar",
        productSuggestion: "ISDIN Fusion Water SPF 50",
        instructions: "Reaplicar cada 2 h.",
      },
      {
        order: 5,
        moment: "evening",
        category: "Limpieza",
        instructions: "Doble limpieza si hubo SPF/maquillaje.",
      },
      {
        order: 6,
        moment: "evening",
        category: "Retinoide",
        productSuggestion: "Retinol 0.3% (3 noches/semana al iniciar)",
        instructions: "Aplicar en piel seca, rostro completo. Pellizco a la vez.",
      },
      {
        order: 7,
        moment: "evening",
        category: "Hidratación reparadora",
        productSuggestion: "Uriage Bariéderm Cica-crema",
        instructions: "Refuerza la barrera tras retinol.",
      },
    ],
  },
];

const now = "2026-05-05T09:00:00Z";

export const mockRecommendations: Recommendation[] = [
  {
    id: "rec_001",
    businessId: mockBusiness.id,
    customerId: "cust_001",
    customerName: "María Fernanda Cabral",
    authorId: "usr_manager_stg",
    authorName: "Ana Guzmán",
    skinType: "sensitive",
    goals: ["Reducir enrojecimiento", "Reforzar barrera"],
    observedConditions: ["cond_rosacea"],
    conditionLabels: ["Rosácea / piel reactiva"],
    productIds: ["prod_lrp_001", "prod_isi_012", "prod_bio_007"],
    routineTemplateId: "rt_sensitive",
    instructions:
      "Iniciar con productos sin perfume. Reevaluar a las 4 semanas. Suspender si aumenta enrojecimiento.",
    followUpAt: "2026-06-15",
    internalNotes: "Cliente con mucha exposición al sol — insistir en SPF mineral.",
    status: "delivered",
    createdAt: "2026-05-04T16:30:00Z",
    updatedAt: "2026-05-04T16:30:00Z",
  },
  {
    id: "rec_002",
    businessId: mockBusiness.id,
    customerId: "cust_002",
    customerName: "Juan Carlos Reyes",
    authorId: "usr_manager_stg",
    authorName: "Ana Guzmán",
    skinType: "oily",
    goals: ["Controlar acné", "Reducir brillo"],
    observedConditions: ["cond_acne"],
    conditionLabels: ["Acné inflamatorio"],
    productIds: ["prod_avn_006", "prod_acm_011", "prod_isd_005"],
    routineTemplateId: "rt_acne_basic",
    instructions:
      "Rutina dual sin combinar peróxido y retinol. SPF 50+ obligatorio.",
    followUpAt: "2026-06-04",
    status: "follow_up",
    createdAt: "2026-04-28T11:30:00Z",
    updatedAt: "2026-04-28T11:30:00Z",
  },
  {
    id: "rec_003",
    businessId: mockBusiness.id,
    customerId: "cust_003",
    customerName: "Roxanna Then",
    authorId: "usr_manager_stg",
    authorName: "Ana Guzmán",
    skinType: "mature",
    goals: ["Tratar manchas", "Firmeza"],
    observedConditions: ["cond_melasma", "cond_aging"],
    conditionLabels: ["Melasma / hiperpigmentación", "Antiedad"],
    productIds: ["prod_eu_002", "prod_ses_003", "prod_vch_009"],
    routineTemplateId: "rt_antiage",
    instructions:
      "Thiamidol mañana + retinol noches alternas. SPF 50+ con reaplicación. Resultados visibles 8-12 semanas.",
    followUpAt: "2026-07-03",
    status: "delivered",
    createdAt: "2026-05-03T15:30:00Z",
    updatedAt: "2026-05-03T15:30:00Z",
  },
  {
    id: "rec_004",
    businessId: mockBusiness.id,
    customerId: "cust_006",
    customerName: "Patricia Bonilla",
    authorId: "usr_manager_stg",
    authorName: "Ana Guzmán",
    skinType: "dry",
    goals: ["Reparar barrera"],
    observedConditions: ["cond_atopic", "cond_dehydration"],
    conditionLabels: ["Dermatitis atópica", "Deshidratación"],
    productIds: ["prod_uri_004", "prod_lrp_001"],
    instructions: "Hidratar 2 veces al día. Evitar agua muy caliente.",
    status: "draft",
    createdAt: now,
    updatedAt: now,
  },
];

export function getRecommendationsByCustomer(customerId: string) {
  return mockRecommendations.filter((r) => r.customerId === customerId);
}
