import type {
  AIActionLog,
  AIAgent,
  ApiKey,
  DgiiSequence,
  ElectronicInvoice,
  Webhook,
  WhatsappConversation,
  WhatsappMessage,
  WhatsappTemplate,
} from "@/types";

export const mockWhatsappTemplates: WhatsappTemplate[] = [
  {
    id: "wat_proforma",
    name: "envio_proforma",
    category: "transactional",
    status: "approved",
    body: "Hola {{1}}, te enviamos tu proforma {{2}} por RD${{3}}. Cualquier consulta respondemos por aquí.",
    language: "es",
    variables: ["customer_name", "proforma_number", "total"],
  },
  {
    id: "wat_invoice",
    name: "envio_factura_ecf",
    category: "transactional",
    status: "approved",
    body: "Hola {{1}}, adjunto tu factura electrónica {{2}}. Gracias por tu compra en DermaLand.",
    language: "es",
    variables: ["customer_name", "ecf_number"],
  },
  {
    id: "wat_birthday",
    name: "felicitacion_cumpleanos",
    category: "marketing",
    status: "approved",
    body: "¡Feliz cumpleaños, {{1}}! 🎉 Tienes 15% de descuento en tu rutina favorita esta semana.",
    language: "es",
    variables: ["customer_name"],
  },
  {
    id: "wat_followup",
    name: "seguimiento_recomendacion",
    category: "service",
    status: "pending",
    body: "Hola {{1}}, ¿cómo te ha ido con la rutina que recomendamos hace {{2}} semanas? Cuéntanos.",
    language: "es",
    variables: ["customer_name", "weeks_since"],
  },
  {
    id: "wat_recall",
    name: "aviso_recall_lote",
    category: "service",
    status: "approved",
    body: "Aviso: el lote {{1}} del producto {{2}} fue retirado por el fabricante. Si lo adquiriste, comunícate con nosotros para reposición.",
    language: "es",
    variables: ["lot_number", "product_name"],
  },
];

export const mockWhatsappConversations: WhatsappConversation[] = [
  {
    id: "wac_001",
    customerId: "cust_001",
    customerName: "María Fernanda Cabral",
    phone: "+18095551101",
    unreadCount: 2,
    lastMessageAt: "2026-05-05T08:55:00Z",
    lastMessagePreview: "Sí, me funcionó muy bien la crema. Quiero pedir más.",
    status: "open",
    assignedTo: "usr_manager_stg",
  },
  {
    id: "wac_002",
    customerId: "cust_002",
    customerName: "Juan Carlos Reyes",
    phone: "+18295551102",
    unreadCount: 0,
    lastMessageAt: "2026-05-04T19:20:00Z",
    lastMessagePreview: "Listo. Mañana paso a recogerlo.",
    status: "closed",
  },
  {
    id: "wac_003",
    customerId: "cust_003",
    customerName: "Roxanna Then",
    phone: "+18095551103",
    unreadCount: 1,
    lastMessageAt: "2026-05-05T09:02:00Z",
    lastMessagePreview: "Quisiera consultar con un especialista — agente IA derivó a humano.",
    status: "handoff",
    assignedTo: "usr_manager_stg",
  },
  {
    id: "wac_004",
    customerName: "+1 829-555-9090",
    phone: "+18295559090",
    unreadCount: 1,
    lastMessageAt: "2026-05-05T08:45:00Z",
    lastMessagePreview: "¿Tienen Bioderma agua micelar disponible?",
    status: "open",
  },
];

export const mockWhatsappMessages: WhatsappMessage[] = [
  {
    id: "wam_001",
    conversationId: "wac_001",
    direction: "outbound",
    body: "Hola María Fernanda, te enviamos tu proforma PROF-2026-00185 por RD$2,340.00.",
    status: "read",
    createdAt: "2026-05-04T16:35:00Z",
  },
  {
    id: "wam_002",
    conversationId: "wac_001",
    direction: "inbound",
    body: "Recibido, gracias!",
    status: "received",
    createdAt: "2026-05-04T16:50:00Z",
  },
  {
    id: "wam_003",
    conversationId: "wac_001",
    direction: "outbound",
    body: "Cualquier duda con la rutina, aquí estamos.",
    status: "delivered",
    createdAt: "2026-05-04T16:51:00Z",
  },
  {
    id: "wam_004",
    conversationId: "wac_001",
    direction: "inbound",
    body: "Sí, me funcionó muy bien la crema. Quiero pedir más.",
    status: "received",
    createdAt: "2026-05-05T08:55:00Z",
  },
];

export const mockAIAgents: AIAgent[] = [
  {
    id: "agent_concierge",
    name: "NAURA — Asistente DermaLand",
    model: "gpt-5.4-mini",
    active: true,
    toolsAllowed: [
      "get_client",
      "search_products",
      "get_inventory_stock",
      "get_product_lots",
      "get_expiring_lots",
      "get_sales_summary",
      "send_whatsapp_message",
      "handoff_to_human",
    ],
    monthlyCallsLimit: 5000,
    monthlyCallsUsed: 142,
    // Prompt oficial NAURA (definido por el negocio), acotado a las capacidades
    // reales de HOY: tools de solo lectura. Lo que aún no existe se orienta al
    // módulo del sistema correspondiente — NAURA nunca promete lo que no puede.
    systemPrompt: [
      "Eres NAURA, el asistente inteligente oficial del sistema DermaLand (tienda dermocosmética en República Dominicana).",
      "Ayudas a médicos, farmacéuticos, cajeros, administradores y personal de ventas a trabajar más rápido, con mayor precisión y siguiendo las políticas de la empresa.",
      "",
      "Prioridades en orden: 1) Exactitud. 2) Seguridad. 3) Rapidez. 4) Facilidad de uso. 5) Consistencia de la información.",
      "",
      "Personalidad: asistente ejecutivo — profesional, claro, amable y preciso, sin respuestas largas innecesarias. Lenguaje sencillo; si la pregunta es compleja, responde por pasos. Español, trato cordial de tú.",
      "",
      "DATOS REALES — usa SIEMPRE tus herramientas antes de responder preguntas de datos; NUNCA inventes productos, precios ni cantidades:",
      "- search_products: buscar productos por nombre o SKU.",
      "- get_inventory_stock: existencia total de un producto.",
      "- get_product_lots: lotes de un producto con vencimiento y cantidad.",
      "- get_expiring_lots: productos vencidos y próximos a vencer.",
      "- get_client: perfil de un cliente (por id, teléfono o documento).",
      "- get_sales_summary: resumen de ventas por período (from/to).",
      "Si un dato no existe en la base de datos, indícalo claramente y ofrece alternativas (otro término de búsqueda o el módulo del sistema donde verlo).",
      "",
      "Capacidades del sistema que HOY se consultan en sus módulos (no las respondas con cifras propias): compras y proveedores → menú Compras; caja y arqueos → Ventas; reportes exportables (PDF/Excel) → Reportes; usuarios, roles, DGII → Administración. Orienta al usuario al módulo correcto.",
      "",
      "Con IA puedes además: explicar productos dermocosméticos y principios activos, interpretar y resumir información, redactar textos y aclarar dudas del personal. NO diagnostiques condiciones médicas: recomienda consultar a un dermatólogo. PROHIBIDO agendar citas — DermaLand no maneja agendamiento. Eres de SOLO LECTURA: nunca modificas información.",
      "",
      "Seguridad: nunca reveles contraseñas, tokens, llaves API, variables de entorno ni información privada. No muestres datos que el usuario no deba consultar.",
      "",
      "Formato para preguntas de datos o análisis:",
      "## Resumen — la respuesta corta con la cifra clave.",
      "## Detalles — información organizada (listas breves).",
      "## Recomendación — qué conviene hacer.",
      "Para saludos o preguntas simples responde directo, sin secciones.",
      "",
      "Sugerencias proactivas: si al consultar detectas algo relevante (lotes vencidos, stock en cero, caída de ventas), menciónalo brevemente al final.",
      "",
      "Montos en RD$ (pesos dominicanos); fechas en DD/MM/AAAA.",
    ].join("\n"),
  },
  {
    id: "agent_inventory_assistant",
    name: "Asistente de inventario",
    model: "gpt-5.4",
    active: false,
    toolsAllowed: [
      "search_products",
      "get_inventory_stock",
      "get_product_lots",
      "get_expiring_lots",
      "get_sales_summary",
      "get_purchase_suggestions",
      "get_inventory_count_summary",
      "get_inventory_count_differences",
    ],
    monthlyCallsLimit: 1000,
    monthlyCallsUsed: 0,
    systemPrompt: [
      "Eres el asistente de inventario de DermaLand para gerentes.",
      "Respondes con datos REALES usando las herramientas: productos vencidos y por vencer (get_expiring_lots), stock por producto, lotes, y resumen de ventas por período.",
      "Nunca inventes cifras; si una consulta no devuelve datos, dilo. Respuestas breves con números concretos y listas. Moneda RD$.",
    ].join("\n"),
  },
];

export const mockAILogs: AIActionLog[] = [
  {
    id: "ail_001",
    agentId: "agent_concierge",
    agentName: "NAURA — Asistente DermaLand",
    customerId: "cust_001",
    tool: "search_products",
    status: "success",
    durationMs: 412,
    costUSD: 0.0021,
    createdAt: "2026-05-05T08:50:00Z",
  },
  {
    id: "ail_002",
    agentId: "agent_concierge",
    agentName: "NAURA — Asistente DermaLand",
    customerId: "cust_003",
    tool: "handoff_to_human",
    status: "handoff",
    durationMs: 218,
    costUSD: 0.0008,
    createdAt: "2026-05-05T09:01:00Z",
  },
  {
    id: "ail_003",
    agentId: "agent_concierge",
    agentName: "NAURA — Asistente DermaLand",
    tool: "get_inventory_stock",
    status: "success",
    durationMs: 305,
    costUSD: 0.0014,
    createdAt: "2026-05-05T08:46:00Z",
  },
];

export const mockApiKeys: ApiKey[] = [
  {
    id: "key_001",
    name: "Sitio web público (lectura catálogo)",
    prefix: "dl_pub_",
    scopes: ["products:read", "locations:read"],
    status: "active",
    lastUsedAt: "2026-05-05T08:30:00Z",
    rateLimitPerMinute: 60,
    createdAt: "2026-05-04T14:00:00Z",
  },
  {
    id: "key_002",
    name: "Integración POS legacy (solo write)",
    prefix: "dl_int_",
    scopes: ["sales:write", "payments:write"],
    status: "revoked",
    lastUsedAt: "2026-04-29T11:15:00Z",
    rateLimitPerMinute: 120,
    createdAt: "2026-04-01T10:00:00Z",
  },
];

export const mockWebhooks: Webhook[] = [
  {
    id: "wh_001",
    url: "https://hooks.dermaland.do/sales-event",
    events: ["proforma.paid", "proforma.converted_to_ecf"],
    status: "active",
    failureCount: 0,
    lastDeliveryAt: "2026-05-05T08:42:18Z",
  },
  {
    id: "wh_002",
    url: "https://hooks.dermaland.do/inventory",
    events: ["product_lot.expiring", "inventory_count.approved"],
    status: "active",
    failureCount: 0,
    lastDeliveryAt: "2026-05-05T09:02:18Z",
  },
  {
    id: "wh_003",
    url: "https://example.com/disabled",
    events: ["proforma.paid"],
    status: "disabled",
    failureCount: 12,
    lastDeliveryAt: "2026-04-22T10:00:00Z",
  },
];

export const mockDgiiSequences: DgiiSequence[] = [
  {
    type: "31",
    label: "Crédito Fiscal",
    rangeStart: 1,
    rangeEnd: 1000,
    nextNumber: 187,
    expiresAt: "2027-12-31",
    status: "active",
  },
  {
    type: "32",
    label: "Consumo",
    rangeStart: 1,
    rangeEnd: 5000,
    nextNumber: 4892,
    expiresAt: "2027-12-31",
    status: "expiring",
  },
  {
    type: "34",
    label: "Nota de Crédito",
    rangeStart: 1,
    rangeEnd: 200,
    nextNumber: 12,
    expiresAt: "2027-12-31",
    status: "active",
  },
  {
    type: "33",
    label: "Nota de Débito",
    rangeStart: 1,
    rangeEnd: 200,
    nextNumber: 1,
    expiresAt: "2027-12-31",
    status: "active",
  },
];

export const mockElectronicInvoices: ElectronicInvoice[] = [
  {
    id: "ecf_001",
    ecfType: "31",
    ecfNumber: "E310000000186",
    customerName: "Distrimedica SRL",
    amount: 9609.32,
    itbis: 1730.68,
    total: 11340,
    status: "accepted",
    trackId: "DGII-TRK-2026-0000186",
    qrCode: "PLACEHOLDER",
    createdAt: "2026-05-04T18:30:00Z",
    submittedAt: "2026-05-04T18:32:11Z",
  },
  {
    id: "ecf_002",
    ecfType: "32",
    ecfNumber: "E320000004891",
    customerName: "María Fernanda Cabral",
    amount: 1983.05,
    itbis: 356.95,
    total: 2340,
    status: "submitted",
    trackId: "DGII-TRK-2026-0004891",
    createdAt: "2026-05-05T09:18:00Z",
    submittedAt: "2026-05-05T09:19:42Z",
  },
  {
    id: "ecf_003",
    ecfType: "32",
    ecfNumber: "E320000004890",
    customerName: "Walk-in",
    amount: 1508.47,
    itbis: 271.53,
    total: 1780,
    status: "rejected",
    trackId: "DGII-TRK-2026-0004890",
    createdAt: "2026-05-05T08:55:00Z",
    submittedAt: "2026-05-05T08:55:42Z",
  },
];
