import type {
  AIActionLog,
  AIAgent,
  ApiKey,
  DgiiSequence,
  ElectronicInvoice,
  Webhook,
  WhatsappConversation,
  WhatsappMessage,
  WhatsappTemplate,
} from "@/types";

export const mockWhatsappTemplates: WhatsappTemplate[] = [
  {
    id: "wat_proforma",
    name: "envio_proforma",
    category: "transactional",
    status: "approved",
    body: "Hola {{1}}, te enviamos tu proforma {{2}} por RD${{3}}. Cualquier consulta respondemos por aquí.",
    language: "es",
    variables: ["customer_name", "proforma_number", "total"],
  },
  {
    id: "wat_invoice",
    name: "envio_factura_ecf",
    category: "transactional",
    status: "approved",
    body: "Hola {{1}}, adjunto tu factura electrónica {{2}}. Gracias por tu compra en DermaLand.",
    language: "es",
    variables: ["customer_name", "ecf_number"],
  },
  {
    id: "wat_birthday",
    name: "felicitacion_cumpleanos",
    category: "marketing",
    status: "approved",
    body: "¡Feliz cumpleaños, {{1}}! 🎉 Tienes 15% de descuento en tu rutina favorita esta semana.",
    language: "es",
    variables: ["customer_name"],
  },
  {
    id: "wat_followup",
    name: "seguimiento_recomendacion",
    category: "service",
    status: "pending",
    body: "Hola {{1}}, ¿cómo te ha ido con la rutina que recomendamos hace {{2}} semanas? Cuéntanos.",
    language: "es",
    variables: ["customer_name", "weeks_since"],
  },
  {
    id: "wat_recall",
    name: "aviso_recall_lote",
    category: "service",
    status: "approved",
    body: "Aviso: el lote {{1}} del producto {{2}} fue retirado por el fabricante. Si lo adquiriste, comunícate con nosotros para reposición.",
    language: "es",
    variables: ["lot_number", "product_name"],
  },
];

export const mockWhatsappConversations: WhatsappConversation[] = [
  {
    id: "wac_001",
    customerId: "cust_001",
    customerName: "María Fernanda Cabral",
    phone: "+18095551101",
    unreadCount: 2,
    lastMessageAt: "2026-05-05T08:55:00Z",
    lastMessagePreview: "Sí, me funcionó muy bien la crema. Quiero pedir más.",
    status: "open",
    assignedTo: "usr_manager_stg",
  },
  {
    id: "wac_002",
    customerId: "cust_002",
    customerName: "Juan Carlos Reyes",
    phone: "+18295551102",
    unreadCount: 0,
    lastMessageAt: "2026-05-04T19:20:00Z",
    lastMessagePreview: "Listo. Mañana paso a recogerlo.",
    status: "closed",
  },
  {
    id: "wac_003",
    customerId: "cust_003",
    customerName: "Roxanna Then",
    phone: "+18095551103",
    unreadCount: 1,
    lastMessageAt: "2026-05-05T09:02:00Z",
    lastMessagePreview: "Quisiera consultar con un especialista — agente IA derivó a humano.",
    status: "handoff",
    assignedTo: "usr_manager_stg",
  },
  {
    id: "wac_004",
    customerName: "+1 829-555-9090",
    phone: "+18295559090",
    unreadCount: 1,
    lastMessageAt: "2026-05-05T08:45:00Z",
    lastMessagePreview: "¿Tienen Bioderma agua micelar disponible?",
    status: "open",
  },
];

export const mockWhatsappMessages: WhatsappMessage[] = [
  {
    id: "wam_001",
    conversationId: "wac_001",
    direction: "outbound",
    body: "Hola María Fernanda, te enviamos tu proforma PROF-2026-00185 por RD$2,340.00.",
    status: "read",
    createdAt: "2026-05-04T16:35:00Z",
  },
  {
    id: "wam_002",
    conversationId: "wac_001",
    direction: "inbound",
    body: "Recibido, gracias!",
    status: "received",
    createdAt: "2026-05-04T16:50:00Z",
  },
  {
    id: "wam_003",
    conversationId: "wac_001",
    direction: "outbound",
    body: "Cualquier duda con la rutina, aquí estamos.",
    status: "delivered",
    createdAt: "2026-05-04T16:51:00Z",
  },
  {
    id: "wam_004",
    conversationId: "wac_001",
    direction: "inbound",
    body: "Sí, me funcionó muy bien la crema. Quiero pedir más.",
    status: "received",
    createdAt: "2026-05-05T08:55:00Z",
  },
];

export const mockAIAgents: AIAgent[] = [
  {
    id: "agent_concierge",
    name: "Concierge dermatológico",
    model: "gpt-4o-mini",
    active: true,
    toolsAllowed: [
      "get_client",
      "search_products",
      "get_product_details",
      "get_inventory_stock",
      "get_expiring_lots",
      "send_whatsapp_message",
      "handoff_to_human",
    ],
    monthlyCallsLimit: 5000,
    monthlyCallsUsed: 142,
    systemPrompt:
      "Eres el asistente conversacional de DermaLand. Ayudas con consultas de productos, stock y derivas a humanos cuando sea necesario. **Prohibido agendar citas** — DermaLand no maneja agendamiento.",
  },
  {
    id: "agent_inventory_assistant",
    name: "Asistente de inventario",
    model: "gpt-4o",
    active: false,
    toolsAllowed: [
      "get_inventory_stock",
      "get_product_lots",
      "get_expiring_lots",
      "get_purchase_suggestions",
      "get_inventory_count_summary",
      "get_inventory_count_differences",
    ],
    monthlyCallsLimit: 1000,
    monthlyCallsUsed: 0,
    systemPrompt:
      "Eres asistente de inventario para gerentes. Resumes alertas de stock, vencimientos y diferencias de conteo.",
  },
];

export const mockAILogs: AIActionLog[] = [
  {
    id: "ail_001",
    agentId: "agent_concierge",
    agentName: "Concierge dermatológico",
    customerId: "cust_001",
    tool: "search_products",
    status: "success",
    durationMs: 412,
    costUSD: 0.0021,
    createdAt: "2026-05-05T08:50:00Z",
  },
  {
    id: "ail_002",
    agentId: "agent_concierge",
    agentName: "Concierge dermatológico",
    customerId: "cust_003",
    tool: "handoff_to_human",
    status: "handoff",
    durationMs: 218,
    costUSD: 0.0008,
    createdAt: "2026-05-05T09:01:00Z",
  },
  {
    id: "ail_003",
    agentId: "agent_concierge",
    agentName: "Concierge dermatológico",
    tool: "get_inventory_stock",
    status: "success",
    durationMs: 305,
    costUSD: 0.0014,
    createdAt: "2026-05-05T08:46:00Z",
  },
];

export const mockApiKeys: ApiKey[] = [
  {
    id: "key_001",
    name: "Sitio web público (lectura catálogo)",
    prefix: "dl_pub_",
    scopes: ["products:read", "locations:read"],
    status: "active",
    lastUsedAt: "2026-05-05T08:30:00Z",
    rateLimitPerMinute: 60,
    createdAt: "2026-05-04T14:00:00Z",
  },
  {
    id: "key_002",
    name: "Integración POS legacy (solo write)",
    prefix: "dl_int_",
    scopes: ["sales:write", "payments:write"],
    status: "revoked",
    lastUsedAt: "2026-04-29T11:15:00Z",
    rateLimitPerMinute: 120,
    createdAt: "2026-04-01T10:00:00Z",
  },
];

export const mockWebhooks: Webhook[] = [
  {
    id: "wh_001",
    url: "https://hooks.dermaland.do/sales-event",
    events: ["proforma.paid", "proforma.converted_to_ecf"],
    status: "active",
    failureCount: 0,
    lastDeliveryAt: "2026-05-05T08:42:18Z",
  },
  {
    id: "wh_002",
    url: "https://hooks.dermaland.do/inventory",
    events: ["product_lot.expiring", "inventory_count.approved"],
    status: "active",
    failureCount: 0,
    lastDeliveryAt: "2026-05-05T09:02:18Z",
  },
  {
    id: "wh_003",
    url: "https://example.com/disabled",
    events: ["proforma.paid"],
    status: "disabled",
    failureCount: 12,
    lastDeliveryAt: "2026-04-22T10:00:00Z",
  },
];

export const mockDgiiSequences: DgiiSequence[] = [
  {
    type: "31",
    label: "Crédito Fiscal",
    rangeStart: 1,
    rangeEnd: 1000,
    nextNumber: 187,
    expiresAt: "2027-12-31",
    status: "active",
  },
  {
    type: "32",
    label: "Consumo",
    rangeStart: 1,
    rangeEnd: 5000,
    nextNumber: 4892,
    expiresAt: "2027-12-31",
    status: "expiring",
  },
  {
    type: "34",
    label: "Nota de Crédito",
    rangeStart: 1,
    rangeEnd: 200,
    nextNumber: 12,
    expiresAt: "2027-12-31",
    status: "active",
  },
  {
    type: "33",
    label: "Nota de Débito",
    rangeStart: 1,
    rangeEnd: 200,
    nextNumber: 1,
    expiresAt: "2027-12-31",
    status: "active",
  },
];

export const mockElectronicInvoices: ElectronicInvoice[] = [
  {
    id: "ecf_001",
    ecfType: "31",
    ecfNumber: "E310000000186",
    customerName: "Distrimedica SRL",
    amount: 9609.32,
    itbis: 1730.68,
    total: 11340,
    status: "accepted",
    trackId: "DGII-TRK-2026-0000186",
    qrCode: "PLACEHOLDER",
    createdAt: "2026-05-04T18:30:00Z",
    submittedAt: "2026-05-04T18:32:11Z",
  },
  {
    id: "ecf_002",
    ecfType: "32",
    ecfNumber: "E320000004891",
    customerName: "María Fernanda Cabral",
    amount: 1983.05,
    itbis: 356.95,
    total: 2340,
    status: "submitted",
    trackId: "DGII-TRK-2026-0004891",
    createdAt: "2026-05-05T09:18:00Z",
    submittedAt: "2026-05-05T09:19:42Z",
  },
  {
    id: "ecf_003",
    ecfType: "32",
    ecfNumber: "E320000004890",
    customerName: "Walk-in",
    amount: 1508.47,
    itbis: 271.53,
    total: 1780,
    status: "rejected",
    trackId: "DGII-TRK-2026-0004890",
    createdAt: "2026-05-05T08:55:00Z",
    submittedAt: "2026-05-05T08:55:42Z",
  },
];
