import type {
  InventoryCount,
  InventoryCountItem,
  InventoryCountScan,
} from "@/types";
import { mockBusiness } from "./tenancy";

const yesterday = "2026-05-04";
const today = "2026-05-05";

export const mockInventoryCounts: InventoryCount[] = [
  {
    id: "ic_2026_05_05_001",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    countNumber: "CONT-2026-05-05-001",
    warehouseId: "wh_stg_main",
    countType: "partial",
    status: "approved",
    assignedTo: ["usr_inv", "usr_cashier_2"],
    startedAt: `${yesterday}T15:30:00Z`,
    submittedAt: `${yesterday}T18:45:00Z`,
    reviewedAt: `${today}T08:50:00Z`,
    approvedAt: `${today}T09:02:00Z`,
    reviewedBy: "usr_supervisor",
    approvedBy: "usr_supervisor",
    notes: "Conteo parcial góndola dermocosmética facial",
    scanCount: 218,
    itemCount: 47,
    createdAt: `${yesterday}T15:30:00Z`,
    updatedAt: `${today}T09:02:00Z`,
  },
  {
    id: "ic_2026_05_05_002",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    countNumber: "CONT-2026-05-05-002",
    warehouseId: "wh_stg_main",
    countType: "spot",
    status: "in_progress",
    assignedTo: ["usr_inv"],
    startedAt: `${today}T08:30:00Z`,
    notes: "Spot check protectores solares",
    scanCount: 24,
    itemCount: 8,
    createdAt: `${today}T08:30:00Z`,
    updatedAt: `${today}T09:15:00Z`,
  },
  {
    id: "ic_2026_05_03_001",
    businessId: mockBusiness.id,
    branchId: "br_sd_naco",
    countNumber: "CONT-2026-05-03-001",
    warehouseId: "wh_naco_main",
    countType: "full",
    status: "approved",
    assignedTo: ["usr_inv"],
    startedAt: "2026-05-03T08:00:00Z",
    submittedAt: "2026-05-03T17:30:00Z",
    reviewedAt: "2026-05-03T18:00:00Z",
    approvedAt: "2026-05-03T18:30:00Z",
    reviewedBy: "usr_supervisor",
    approvedBy: "usr_admin",
    notes: "Inventario inicial Naco",
    scanCount: 1342,
    itemCount: 286,
    createdAt: "2026-05-03T08:00:00Z",
    updatedAt: "2026-05-03T18:30:00Z",
  },
  {
    id: "ic_2026_05_06_001",
    businessId: mockBusiness.id,
    branchId: "br_santiago",
    countNumber: "CONT-2026-05-06-001",
    warehouseId: "wh_stg_main",
    countType: "full",
    status: "draft",
    assignedTo: ["usr_inv", "usr_cashier_1", "usr_cashier_2"],
    notes: "Conteo total mensual programado",
    scanCount: 0,
    itemCount: 0,
    createdAt: `${today}T07:00:00Z`,
    updatedAt: `${today}T07:00:00Z`,
  },
];

// Items del conteo aprobado del día anterior (mostrar diferencias)
export const mockCountItems: InventoryCountItem[] = [
  {
    id: "ici_001",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_lrp_001",
    productSku: "DERM-000034",
    productName: "La Roche-Posay Toleriane Sensitive Crema 40 ml",
    productLotId: "lot_lrp_001a",
    lotNumber: "LRP24A",
    expiresAt: "2026-06-19",
    warehouseId: "wh_stg_main",
    expectedQuantity: 20,
    countedQuantity: 18,
    differenceQuantity: -2,
    status: "shortage",
    lastScanAt: `${yesterday}T17:14:00Z`,
  },
  {
    id: "ici_002",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_eu_002",
    productSku: "DERM-000018",
    productName: "Eucerin Sun Protection Pigment Control SPF 50+ 50 ml",
    productLotId: "lot_eu_002a",
    lotNumber: "EU23X",
    expiresAt: "2026-04-20",
    warehouseId: "wh_stg_main",
    expectedQuantity: 8,
    countedQuantity: 6,
    differenceQuantity: -2,
    status: "expired",
    lastScanAt: `${yesterday}T17:22:00Z`,
  },
  {
    id: "ici_003",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_ses_003",
    productSku: "DERM-000091",
    productName: "Sesderma C-VIT Sérum Liposomal 30 ml",
    productLotId: "lot_ses_003a",
    lotNumber: "SES24-CV",
    expiresAt: "2026-11-01",
    warehouseId: "wh_stg_main",
    expectedQuantity: 9,
    countedQuantity: 9,
    differenceQuantity: 0,
    status: "match",
    lastScanAt: `${yesterday}T17:30:00Z`,
  },
  {
    id: "ici_004",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_uri_004",
    productSku: "DERM-000122",
    productName: "Uriage Bariéderm Cica-Crema 100 ml",
    productLotId: "lot_uri_004a",
    lotNumber: "URI24-BAR",
    expiresAt: "2027-10-28",
    warehouseId: "wh_stg_main",
    expectedQuantity: 12,
    countedQuantity: 14,
    differenceQuantity: 2,
    status: "overage",
    lastScanAt: `${yesterday}T17:40:00Z`,
  },
  {
    id: "ici_005",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_acm_011",
    productSku: "DERM-000523",
    productName: "ACM Sebionex Gel limpiador 200 ml",
    productLotId: "lot_acm_011a",
    lotNumber: "ACM24-SEB",
    expiresAt: "2027-07-05",
    warehouseId: "wh_stg_main",
    expectedQuantity: 7,
    countedQuantity: 5,
    differenceQuantity: -2,
    status: "shortage",
    lastScanAt: `${yesterday}T17:55:00Z`,
  },
  {
    id: "ici_006",
    inventoryCountId: "ic_2026_05_05_001",
    productId: "prod_cer_008",
    productSku: "DERM-000356",
    productName: "CeraVe Limpiador Hidratante 236 ml",
    productLotId: "lot_cer_008a",
    lotNumber: "CER24-HC",
    expiresAt: "2027-10-28",
    warehouseId: "wh_stg_main",
    expectedQuantity: 30,
    countedQuantity: 31,
    differenceQuantity: 1,
    status: "overage",
    lastScanAt: `${yesterday}T18:02:00Z`,
  },
];

export const mockCountScans: InventoryCountScan[] = mockCountItems.flatMap(
  (item, ix) =>
    Array.from({ length: Math.min(item.countedQuantity, 5) }).map((_, i) => ({
      id: `scan_${ix}_${i}`,
      inventoryCountId: item.inventoryCountId,
      productId: item.productId,
      productLotId: item.productLotId,
      branchId: "br_santiago",
      warehouseId: item.warehouseId,
      barcode: `8432598${ix}${i}5`,
      scannedQuantity: 1,
      scanSource: i === 0 ? ("camera" as const) : ("bluetooth_scanner" as const),
      scannedBy: "usr_inv",
      scannedByName: "Carlos Mejía",
      scannedAt: item.lastScanAt ?? `${yesterday}T17:00:00Z`,
      deviceId: "dev_pixel8_carlos",
      offlineScanId: `off_${ix}_${i}`,
      syncStatus: "synced" as const,
    })),
);

export function getInventoryCountById(id: string) {
  return mockInventoryCounts.find((c) => c.id === id);
}

export function getItemsForCount(countId: string) {
  return mockCountItems.filter((i) => i.inventoryCountId === countId);
}

export function getScansForCount(countId: string) {
  return mockCountScans.filter((s) => s.inventoryCountId === countId);
}
