import type { InventoryMovement } from "@/types";
import { mockBusiness } from "./tenancy";

const branch = "br_santiago";
const wh = "wh_stg_main";

export const mockInventoryMovements: InventoryMovement[] = [
  {
    id: "mov_002150",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_lrp_001",
    lotId: "lot_lrp_001a",
    warehouseId: wh,
    type: "exit_sale",
    quantity: -1,
    reference: "PROF-2026-00185",
    userId: "usr_cashier_1",
    userName: "Rosa Peralta",
    createdAt: "2026-05-05T09:18:00Z",
  },
  {
    id: "mov_002149",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_eu_002",
    lotId: "lot_eu_002a",
    warehouseId: wh,
    type: "expiry",
    quantity: -2,
    reason: "Lote EU23X vencido — 15 días",
    userId: "usr_inv",
    userName: "Carlos Mejía",
    createdAt: "2026-05-05T07:42:00Z",
  },
  {
    id: "mov_002148",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_isd_005",
    lotId: "lot_isd_005a",
    warehouseId: wh,
    type: "quarantine",
    quantity: -24,
    reason: "Pendiente verificación de cadena de frío",
    userId: "usr_inv",
    userName: "Carlos Mejía",
    createdAt: "2026-05-04T18:20:00Z",
  },
  {
    id: "mov_002147",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_avn_006",
    lotId: "lot_avn_006a",
    warehouseId: wh,
    type: "exit_sale",
    quantity: -1,
    reference: "PROF-2026-00185",
    userId: "usr_cashier_1",
    userName: "Rosa Peralta",
    createdAt: "2026-05-05T09:18:00Z",
  },
  {
    id: "mov_002146",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_acm_011",
    lotId: "lot_acm_011a",
    warehouseId: wh,
    type: "exit_sale",
    quantity: -2,
    reference: "PROF-2026-00186",
    userId: "usr_cashier_1",
    userName: "Rosa Peralta",
    createdAt: "2026-05-05T09:42:00Z",
  },
  {
    id: "mov_002145",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_eu_002",
    lotId: "lot_eu_002a",
    warehouseId: wh,
    type: "adjustment_negative",
    quantity: -2,
    reason: "Ajuste por conteo físico CONT-2026-05-05-001",
    reference: "ic_2026_05_05_001",
    userId: "usr_supervisor",
    userName: "María Torres",
    createdAt: "2026-05-05T09:02:00Z",
  },
  {
    id: "mov_002144",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_uri_004",
    lotId: "lot_uri_004a",
    warehouseId: wh,
    type: "adjustment_positive",
    quantity: 2,
    reason: "Ajuste por conteo físico CONT-2026-05-05-001 — sobrante",
    reference: "ic_2026_05_05_001",
    userId: "usr_supervisor",
    userName: "María Torres",
    createdAt: "2026-05-05T09:02:00Z",
  },
  {
    id: "mov_002143",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_lrp_001",
    lotId: "lot_lrp_001b",
    warehouseId: wh,
    type: "entry_purchase",
    quantity: 24,
    reference: "OC-2026-00045",
    userId: "usr_inv",
    userName: "Carlos Mejía",
    createdAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "mov_002142",
    businessId: mockBusiness.id,
    branchId: branch,
    productId: "prod_isi_012",
    lotId: "lot_isi_012a",
    warehouseId: wh,
    type: "quarantine",
    quantity: -8,
    reason: "Recall fabricante por irregularidad de envasado",
    userId: "usr_inv",
    userName: "Carlos Mejía",
    createdAt: "2026-05-04T11:30:00Z",
  },
];
