import type { Plan, Subscription, UsageCounter } from "@/types";

export const mockPlans: Plan[] = [
  {
    id: "plan_basic",
    name: "Básico",
    monthlyPriceUSD: 39,
    features: [
      "1 sucursal",
      "5 usuarios",
      "Inventario básico",
      "POS sin DGII",
      "Soporte email",
    ],
    limits: {
      users: 5,
      branches: 1,
      products: 1500,
      customers: 5000,
      whatsappMessages: 0,
      apiRequests: 0,
      storageGB: 1,
      reportsAdvanced: false,
      aiEnabled: false,
      dgiiEnabled: false,
    },
  },
  {
    id: "plan_pro",
    name: "Pro",
    monthlyPriceUSD: 99,
    features: [
      "Hasta 3 sucursales",
      "20 usuarios",
      "Inventario por lote + conteo móvil",
      "Reportes",
      "WhatsApp 1k msg/mes",
    ],
    limits: {
      users: 20,
      branches: 3,
      products: 8000,
      customers: 25000,
      whatsappMessages: 1000,
      apiRequests: 50000,
      storageGB: 10,
      reportsAdvanced: true,
      aiEnabled: false,
      dgiiEnabled: true,
    },
  },
  {
    id: "plan_business",
    name: "Business / POS",
    monthlyPriceUSD: 199,
    features: [
      "Hasta 10 sucursales",
      "50 usuarios",
      "DGII e-CF activo",
      "WhatsApp 10k msg/mes",
      "Conteo móvil PWA con offline",
      "API V3",
    ],
    limits: {
      users: 50,
      branches: 10,
      products: 25000,
      customers: 100000,
      whatsappMessages: 10000,
      apiRequests: 250000,
      storageGB: 50,
      reportsAdvanced: true,
      aiEnabled: false,
      dgiiEnabled: true,
    },
    highlight: true,
  },
  {
    id: "plan_premium_ai",
    name: "Premium IA",
    monthlyPriceUSD: 349,
    features: [
      "Todo de Business",
      "Agentes IA con tools",
      "Recomendaciones IA",
      "Webhooks ilimitados",
    ],
    limits: {
      users: 100,
      branches: 20,
      products: 100000,
      customers: 500000,
      whatsappMessages: 30000,
      apiRequests: 1000000,
      storageGB: 200,
      reportsAdvanced: true,
      aiEnabled: true,
      dgiiEnabled: true,
    },
  },
  {
    id: "plan_enterprise",
    name: "Enterprise",
    monthlyPriceUSD: 0, // custom pricing
    features: [
      "Personalización",
      "SLA dedicado",
      "Soporte 24/7",
      "Integraciones a medida",
    ],
    limits: {
      users: 1000,
      branches: 100,
      products: 1000000,
      customers: 5000000,
      whatsappMessages: 1000000,
      apiRequests: 100000000,
      storageGB: 1000,
      reportsAdvanced: true,
      aiEnabled: true,
      dgiiEnabled: true,
    },
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub_dermaland",
    businessId: "biz_dermaland",
    businessName: "DermaLand",
    planId: "plan_business",
    planName: "Business / POS",
    status: "trial",
    trialEndsAt: "2026-06-04T00:00:00Z",
    currentPeriodStart: "2026-05-04T00:00:00Z",
    currentPeriodEnd: "2026-06-04T00:00:00Z",
    monthlyPriceUSD: 199,
    paymentMethod: "manual",
  },
  {
    id: "sub_farmadream",
    businessId: "biz_farmadream",
    businessName: "Farmadream Higüey",
    planId: "plan_pro",
    planName: "Pro",
    status: "active",
    currentPeriodStart: "2026-04-15T00:00:00Z",
    currentPeriodEnd: "2026-05-15T00:00:00Z",
    monthlyPriceUSD: 99,
    paymentMethod: "paypal",
    lastPaymentAt: "2026-04-15T10:00:00Z",
  },
  {
    id: "sub_purite",
    businessId: "biz_purite",
    businessName: "Pur'ité Cosmética",
    planId: "plan_basic",
    planName: "Básico",
    status: "past_due",
    currentPeriodStart: "2026-03-20T00:00:00Z",
    currentPeriodEnd: "2026-04-20T00:00:00Z",
    monthlyPriceUSD: 39,
    paymentMethod: "manual",
    lastPaymentAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "sub_alborada",
    businessId: "biz_alborada",
    businessName: "Farmacia La Alborada",
    planId: "plan_premium_ai",
    planName: "Premium IA",
    status: "active",
    currentPeriodStart: "2026-04-29T00:00:00Z",
    currentPeriodEnd: "2026-05-29T00:00:00Z",
    monthlyPriceUSD: 349,
    paymentMethod: "paypal",
    lastPaymentAt: "2026-04-29T15:00:00Z",
  },
];

export const mockUsageCounters: UsageCounter[] = [
  {
    businessId: "biz_dermaland",
    metric: "users",
    used: 7,
    limit: 50,
    resetAt: "2026-06-04",
  },
  {
    businessId: "biz_dermaland",
    metric: "products",
    used: 1342,
    limit: 25000,
    resetAt: "2026-06-04",
  },
  {
    businessId: "biz_dermaland",
    metric: "customers",
    used: 6,
    limit: 100000,
    resetAt: "2026-06-04",
  },
  {
    businessId: "biz_dermaland",
    metric: "whatsappMessages",
    used: 142,
    limit: 10000,
    resetAt: "2026-06-04",
  },
  {
    businessId: "biz_dermaland",
    metric: "apiRequests",
    used: 0,
    limit: 250000,
    resetAt: "2026-06-04",
  },
  {
    businessId: "biz_dermaland",
    metric: "storageGB",
    used: 0.4,
    limit: 50,
    resetAt: "2026-06-04",
  },
];

export const mockPlatformBusinesses = [
  {
    id: "biz_dermaland",
    name: "DermaLand",
    plan: "Business / POS",
    status: "trial" as const,
    branches: 3,
    users: 7,
    monthlyRevenue: 0,
    country: "RD",
    createdAt: "2026-05-04",
  },
  {
    id: "biz_farmadream",
    name: "Farmadream Higüey",
    plan: "Pro",
    status: "active" as const,
    branches: 2,
    users: 12,
    monthlyRevenue: 99,
    country: "RD",
    createdAt: "2025-10-12",
  },
  {
    id: "biz_purite",
    name: "Pur'ité Cosmética",
    plan: "Básico",
    status: "past_due" as const,
    branches: 1,
    users: 4,
    monthlyRevenue: 39,
    country: "RD",
    createdAt: "2025-08-04",
  },
  {
    id: "biz_alborada",
    name: "Farmacia La Alborada",
    plan: "Premium IA",
    status: "active" as const,
    branches: 5,
    users: 28,
    monthlyRevenue: 349,
    country: "RD",
    createdAt: "2025-06-30",
  },
];
